home/urls.py
from django.urls import path
from home import views as home_views

app_name = "home"

urlpatterns = [
    path(
        "",
        view=home_views.IndexView.as_view(),
        name="index",
    ),
    path(
        "about-us/",
        view=home_views.AboutView.as_view(),
        name="about",
    ),
    path(
        "dashboard/",
        view=home_views.DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "search/",
        view=home_views.SearchView.as_view(),
        name="search",
    )
]

listing/urls.py
from django.urls import path
from listing import views as listing_views

app_name = "listing"

urlpatterns = [
    path(
        "",
        view=listing_views.ListingView.as_view(),
        name="listing-list"
    ),
    path(
        "<slug:slug>/",
        view=listing_views.ListingDetailView.as_view(),
        name="listing-detail"
    )
]

home/models.py
import auto_prefetch
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

from listing.models import Listing

from realestate.utils.models import TimeBasedModel
from realestate.utils.choices import Gender
from realestate.utils.media import get_image_upload_path



# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class CustomUser(TimeBasedModel, AbstractUser):
    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=15, null=True, blank=True)


    objects = UserManager()

    @property
    def is_realtor(self):
        return hasattr(self, "realtor")
        
    class Meta(auto_prefetch.Model.Meta):
        ordering = ["first_name", "last_name"]
        verbose_name = "user"

    def __str__(self):
        return self.get_full_name() or self.email

class Realtor(TimeBasedModel):
    user = auto_prefetch.OneToOneField("home.CustomUser", on_delete=models.CASCADE)
    about = models.TextField(max_length=500, null=True, blank=True)
    gender = models.CharField(
        max_length=15, choices=Gender.choices
    )
    profile_pic = models.ImageField(
        upload_to=get_image_upload_path,
        blank=True,
        verbose_name="Profile Picture",
        null=True,
    )
    is_mvp = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.user}"

    @property
    def image_url(self):
        """return image if it exists otherwise use a default"""
        if self.profile_pic:
            return self.profile_pic.url

        return f"{settings.STATIC_URL}img/realtors/default_avatar.png"


class Contact(TimeBasedModel):
    user = auto_prefetch.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank = True
    )
    listing = auto_prefetch.ForeignKey(
        Listing,
        on_delete=models.CASCADE,
        null=True
    )
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    message = models.TextField()


    def __str__(self):
        return self.listing.title

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from home.models import CustomUser, Contact
from listing.models import Listing
from realestate.utils.forms import CssForm


class CustomSignupForm(CssForm, UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'first_name', 
            'last_name', 
            'username', 
            'email', 
            'password1', 
            'password2'
        ]


class ContactForm(CssForm, forms.ModelForm):
    listing = forms.ModelChoiceField(
       queryset=Listing.objects.none(),
       empty_label=None,
       widget=forms.Select(
            attrs={
                # 'readonly': True,

            }
       )
    )
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'phone',
            'message'

        ]

        labels = {
            'listing': 'property',
        }

        widgets = { 
            'message': forms.Textarea(
                attrs={
                    'rows':3,
                    'cols':20,
                }
            )
        }

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView
from home.models import Realtor, Contact
from listing.models import Listing
from realestate.utils.choices import ListingStatus, PriceChoices, BedRoomChoices, StateChoices
# Create your views here.



class IndexView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        listings = Listing.objects.select_related('realtor__user') \
            .order_by('-created_at') \
            .filter(status=ListingStatus.Published)[:3]
        
        context.update({
        "listings":listings,
        'PriceChoices':PriceChoices,
        'BedRoomChoices':BedRoomChoices,
        'StateChoices':StateChoices,
        })

        return context

class AboutView(TemplateView):
    template_name = 'home/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mvp_realtor = Realtor.items.filter(is_mvp=True).first()
        realtors = Realtor.items.select_related('user').order_by('-created_at')
        context.update({
        "mvp_realtor":mvp_realtor,
        "realtors":realtors,
        })

        return context


class DashboardView(LoginRequiredMixin, ListView):
    template_name = 'home/dashboard.html'
    model = Contact
    context_object_name = 'contacts'
    paginate_by = 9

    def get_queryset(self):
        queryset = Contact.objects.order_by('created_at') \
            .filter(user=self.request.user)


        return queryset


class SearchView(TemplateView):
    template_name = 'home/search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request = self.request
        listings = Listing.objects.select_related('realtor__user') \
            .order_by('-created_at') \
            .filter(status=ListingStatus.Published)
        
        keywords = request.GET.get('keywords')
        city = request.GET.get('city')
        state = request.GET.get('state')
        bedrooms = request.GET.get('bedrooms')
        price = request.GET.get('price')

        def is_validparam(param):
            return param != '' and param is not None

        if is_validparam(keywords):
            listings = listings.filter(description__icontains=keywords)
            
        if is_validparam(city):
            listings = listings.filter(city__iexact=city)

        if is_validparam(state):
            listings = listings.filter(state__iexact=state)

        if is_validparam(bedrooms):
            listings = listings.filter(bedrooms__lte=bedrooms)

        if is_validparam(price):
            listings = listings.filter(price__lte=price)
    

        context.update({
        'listings':listings,
        'PriceChoices':PriceChoices,
        'BedRoomChoices':BedRoomChoices,
        'StateChoices':StateChoices,
        'keywords':keywords,
        'bedrooms':bedrooms,
        'city':city,
        'price':price,
        'state':state,
        })

        return context

home/templates/home/about.html
{% extends 'partials/_base.html' %}
{% load static %}
{% block title %}About{% endblock title %}

{% block body %}

<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">About BT Real Estate</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> About</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="about" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>We Search For The Perfect Home</h2>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
          <img src="{% static 'img/about.jpg' %}" alt="">
          <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis esse officia repudiandae ad saepe ex, amet
            neque quod accusamus rem quia magnam magni dolorum facilis ullam minima perferendis? Exercitationem at quaerat
            commodi id libero eveniet harum perferendis laborum molestias quia.</p>
        </div>
        {% if mvp_realtor %}
        <div class="col-md-4">
          <div class="card">
            <img class="card-img-top" src="{{mvp_realtor.image_url}}" alt="Seller of the month">
            <div class="card-body">
              <h5 class="card-title">Seller Of The Month</h5>
              <h6 class="text-secondary">{{mvp_realtor}}</h6>
              <p class="card-text">{{mvp_realtor.about}}
              </p>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </section>

  <!-- Work -->
  <section id="work" class="bg-dark text-white text-center">
    <h2 class="display-4">We Work For You</h2>
    <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
    <hr>
    <a href="listings.html" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
  </section>

  <!-- Team -->
  <section id="team" class="py-5">
    <div class="container">
      <h2 class="text-center">Our Team</h2>
      <div class="row text-center">
        {% for realtor in realtors %}
          <div class="col-md-4">
            <img src="{{realtor.image_url}}" alt="" class="rounded-circle mb-3">
            <h4>{{realtor}}</h4>
            <p class="text-success">
              <i class="fas fa-award text-success mb-3"></i> Realtor </p>
            <hr>
            <p>
              <i class="fas fa-phone"></i> {{realtor.phone}}</p>
            <p>
              <i class="fas fa-envelope-open"></i> {{realtor.user.email}}</p>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock body %}

home/templates/home/dashboard.html
{% extends 'partials/_base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}

{% block body %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">User Dashboard</h1>
          <p class="lead">Manage your BT Real Estate account</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>
  {% include 'partials/_messages.html' %}


  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome {{request.user}}</h2>
          <p>Here are the property listings that you have inquired about</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Property</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for contact in contacts %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{contact.listing.title}}</td>
                <td>
                  <a class="btn btn-light" href="{% url 'listing:listing-detail' contact.listing.slug %}">View Listing</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

{% endblock body %}

home/templates/home/search.html
{% extends 'partials/_base.html' %}
{% load static humanize %}
{% block title %}Search{% endblock title %}

{% block body %}
      <!-- Showcase -->
  <section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container text-center">
      <div class="row text-center">
        <div class="col-md-12">
        
            <form action="">
              <!-- Form Row 1 -->
              <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Keywords</label>
                  <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)" value="{% if keywords %}{{keywords}}{% endif %}">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <input type="text" name="city" class="form-control" placeholder="City" value={% if city %}{{city}}{% endif %}>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">State</label>
                  <select name="state" class="form-control">
                    <option selected="true" disabled="disabled">State (All)</option>
                    {% for key, val in StateChoices.choices %}
                      <option value="{{key}}" {% if key == state %}selected{% endif %}>{{val}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->
              <div class="form-row">
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Bedrooms</label>
                  <select name="bedrooms" class="form-control">
                    <option selected="true" disabled="disabled">Bedrooms (All)</option>
                    {% for key, val in BedRoomChoices.choices %}
                      <option value="{{key}}" {% if bedrooms == key %}selected{% endif %}>{{val}}</option>
                    {% endfor %}
                    
                  </select>
                </div>
                <div class="col-md-6 mb-3">
                  <select name="price" class="form-control" id="type">
                    <option selected="true" disabled="disabled">Max Price (Any)</option>
                    {% for key, val in PriceChoices.choices %}
                    <option value="{{key}}" {% if price == key %}selected{% endif %}>{{val}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
        </div>
      </div>
    </div>
  </section>

   <!-- Breadcrumb -->
   <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="listings.html">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">

        <!-- Listings -->
        {% for listing in listings  %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src="{{listing.photo_main.url}}" alt="">
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white">${{listing.price|intcomma}}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i> {{listing.address}} </p>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}} </div>
                <div class="col-6">
                  <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
              </div>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                <div class="col-6">
                  <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-12">
                  <i class="fas fa-user"></i> {{listing.realtor}} </div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-12">
                  <i class="fas fa-clock"></i> {{listing.created_at|timesince}} ago</div>
              </div>
              <hr>
              <a href="{% url 'listing:listing-detail' listing.slug %}" class="btn btn-primary btn-block">More Info</a>
            </div>
          </div>
        </div>
        {% empty %}
        <div class="col-12">
            <h3 class="text-center">Oops can't find the listing you're looking for</h3>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>

{% endblock body %}