home/urls.py
from django.urls import path
from home import views as home_views

app_name = "home"

urlpatterns = [
    path(
        "",
        view=home_views.IndexView.as_view(),
        name="index",
    ),
    path(
        "about-us/",
        view=home_views.AboutView.as_view(),
        name="about",
    ),
    path(
        "dashboard/",
        view=home_views.DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "search/",
        view=home_views.SearchView.as_view(),
        name="search",
    )
]

listing/urls.py
from django.urls import path
from listing import views as listing_views

app_name = "listing"

urlpatterns = [
    path(
        "",
        view=listing_views.ListingView.as_view(),
        name="listing-list"
    ),
    path(
        "<slug:slug>/",
        view=listing_views.ListingDetailView.as_view(),
        name="listing-detail"
    )
]

home/models.py
import auto_prefetch
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

from listing.models import Listing

from realestate.utils.models import TimeBasedModel
from realestate.utils.choices import Gender
from realestate.utils.media import get_image_upload_path



# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class CustomUser(TimeBasedModel, AbstractUser):
    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=15, null=True, blank=True)


    objects = UserManager()

    @property
    def is_realtor(self):
        return hasattr(self, "realtor")
        
    class Meta(auto_prefetch.Model.Meta):
        ordering = ["first_name", "last_name"]
        verbose_name = "user"

    def __str__(self):
        return self.get_full_name() or self.email

class Realtor(TimeBasedModel):
    user = auto_prefetch.OneToOneField("home.CustomUser", on_delete=models.CASCADE)
    about = models.TextField(max_length=500, null=True, blank=True)
    gender = models.CharField(
        max_length=15, choices=Gender.choices
    )
    profile_pic = models.ImageField(
        upload_to=get_image_upload_path,
        blank=True,
        verbose_name="Profile Picture",
        null=True,
    )
    is_mvp = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.user}"

    @property
    def image_url(self):
        """return image if it exists otherwise use a default"""
        if self.profile_pic:
            return self.profile_pic.url

        return f"{settings.STATIC_URL}img/realtors/default_avatar.png"


class Contact(TimeBasedModel):
    user = auto_prefetch.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank = True
    )
    listing = auto_prefetch.ForeignKey(
        Listing,
        on_delete=models.CASCADE,
        null=True
    )
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    message = models.TextField()


    def __str__(self):
        return self.listing.title

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from home.models import CustomUser, Contact
from listing.models import Listing
from realestate.utils.forms import CssForm


class CustomSignupForm(CssForm, UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            'first_name', 
            'last_name', 
            'username', 
            'email', 
            'password1', 
            'password2'
        ]


class ContactForm(CssForm, forms.ModelForm):
    listing = forms.ModelChoiceField(
       queryset=Listing.objects.none(),
       empty_label=None,
       widget=forms.Select(
            attrs={
                # 'readonly': True,

            }
       )
    )
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'phone',
            'message'

        ]

        labels = {
            'listing': 'property',
        }

        widgets = { 
            'message': forms.Textarea(
                attrs={
                    'rows':3,
                    'cols':20,
                }
            )
        }

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView
from home.models import Realtor, Contact
from listing.models import Listing
from realestate.utils.choices import ListingStatus, PriceChoices, BedRoomChoices, StateChoices
# Create your views here.



class IndexView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        listings = Listing.objects.select_related('realtor__user') \
            .order_by('-created_at') \
            .filter(status=ListingStatus.Published)[:3]
        
        context.update({
        "listings":listings,
        'PriceChoices':PriceChoices,
        'BedRoomChoices':BedRoomChoices,
        'StateChoices':StateChoices,
        })

        return context

class AboutView(TemplateView):
    template_name = 'home/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mvp_realtor = Realtor.items.filter(is_mvp=True).first()
        realtors = Realtor.items.select_related('user').order_by('-created_at')
        context.update({
        "mvp_realtor":mvp_realtor,
        "realtors":realtors,
        })

        return context


class DashboardView(LoginRequiredMixin, ListView):
    template_name = 'home/dashboard.html'
    model = Contact
    context_object_name = 'contacts'
    paginate_by = 9

    def get_queryset(self):
        queryset = Contact.objects.order_by('created_at') \
            .filter(user=self.request.user)


        return queryset


class SearchView(TemplateView):
    template_name = 'home/search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request = self.request
        listings = Listing.objects.select_related('realtor__user') \
            .order_by('-created_at') \
            .filter(status=ListingStatus.Published)
        
        keywords = request.GET.get('keywords')
        city = request.GET.get('city')
        state = request.GET.get('state')
        bedrooms = request.GET.get('bedrooms')
        price = request.GET.get('price')

        def is_validparam(param):
            return param != '' and param is not None

        if is_validparam(keywords):
            listings = listings.filter(description__icontains=keywords)
            
        if is_validparam(city):
            listings = listings.filter(city__iexact=city)

        if is_validparam(state):
            listings = listings.filter(state__iexact=state)

        if is_validparam(bedrooms):
            listings = listings.filter(bedrooms__lte=bedrooms)

        if is_validparam(price):
            listings = listings.filter(price__lte=price)
    

        context.update({
        'listings':listings,
        'PriceChoices':PriceChoices,
        'BedRoomChoices':BedRoomChoices,
        'StateChoices':StateChoices,
        'keywords':keywords,
        'bedrooms':bedrooms,
        'city':city,
        'price':price,
        'state':state,
        })

        return context

home/templates/partials/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% include 'partials/_stylesheets.html' %}
  <title>{% block title %}{% endblock title %} | Real Estate</title>
</head>

<body>

    {% include 'partials/_navbar.html' %}

    {% block body %}
    
    {% endblock body %}


    {% include 'partials/_footer.html' %}


{% include 'partials/_scripts.html' %}
{% block scripts %}{% endblock scripts %}
</body>

</html>

home/templates/partials/_footer.html
 <!-- Footer -->
 <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year">{% now 'Y' %}</span> BT Real Estate
  </footer>

home/templates/partials/_form_errors.html
{% if redirect_field_value %}
<input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
{% endif %}

{{ form.media }}
{% csrf_token %}

{% if form.errors %}
  <div class="col-md-12 justify-content-center">

    <div
      class="alert alert-danger alert-dismissible text-center">
      {% for field in form %}
      {% for error in field.errors %}
      <span class="text-sm"><i class="fa fa-times"></i>&nbsp;&nbsp;<strong>{{ field.label }}</strong>: {{ error|escape }}</span><br>
      {% endfor %}
      {% endfor %}

      {% for error in form.non_field_errors %}
      <i class="text-sm"><strong>{{ error|escape }}</strong></i><br>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</span></button>
    </div>
</div>

{% endif %}

home/templates/partials/_messages.html
    {% if messages %}
      {% for message in messages %}
      <div id="message" class="container">
        {% if forloop.counter == messages|length %}
        <div class="alert alert-{{ message.tags|default:'error' }} alert-dismissible text-center" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</span></button>
        </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>

home/templates/partials/_navbar.html
{% load static %}
  <!-- Top Bar -->
  <section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (617)-555-5555
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> contact@btrealestate.co
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fab fa-pinterest"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'home:index' %}">Home</a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'home:about' %}">About</a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'listing:listing-list' %}">Featured Listings</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'home:dashboard' %}">
              Welcome {{request.user}} (Dashboard)
            </a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'account_logout' %}">
              <i class="fas fa-sign-out-alt"></i>
              Logout
            </a>
          </li>
          {% else %}
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'account_signup' %}">
              <i class="fas fa-user-plus"></i> Register</a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'account_login' %}">
              <i class="fas fa-sign-in-alt"></i>

              Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

home/templates/partials/_pagination.html
{% if is_paginated %}
<div class="row">
    <div class="col-md-12">
        {% if page_obj.has_other_pages %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
            {% endif %}
            
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{i}}">{{i}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{i}}">{{i}}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&raquo;</a>
                </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
{% endif %}

home/templates/partials/_scripts.html
{% load static %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% comment %} <script src="{% static 'glightbox/js/glightbox.js' %}"></script> {% endcomment %}
<script src="{% static 'js/lightbox.min.js' %}"></script>


<script>
    $(document).ready(function(){
        let url = $("a[href='{{request.path}}']");
        $(url).addClass("active");
        
        $(".alert").delay(10000).slideUp(200, function () {
          $(this).alert('close');
        });
      }) 
</script>

home/templates/partials/_stylesheets.html
{% load static %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'css/all.css' %}">
<!-- Bootstrap -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<!-- Custom -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
<link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">

{% comment %} <link rel="stylesheet" href="{% static 'glightbox/css/glightbox.css' %}"> {% endcomment %}